In [2]:
import pandas as pd
import numpy as np

# Generate 1,000 samples from a normal distribution
heights = np.random.normal(loc=170, scale=10, size=1000)
weights = np.random.normal(loc=70, scale=15, size=1000)

# Create a correlation between height and weight
weights += (heights - 170) * 0.5
df = pd.DataFrame({'Height': heights, 'Weight': weights})

# Add categorical data
genders = np.random.choice(['Male', 'Female'], size=1000)
df['Gender'] = genders
df.head()

       Height     Weight  Gender
0  180.642343  71.796695  Female
1  159.671988  69.360861    Male
2  173.070174  74.058238    Male
3  173.718081  55.682485  Female
4  166.712283  40.192593    Male

In [3]:
import numpy as np
import pandas as pd

def generate_customer_data(num_records):
    data = []
    for _ in range(num_records):
        age = np.random.randint(18, 80)
       
        # Rule: Income is loosely based on age
        base_income = 20000 + (age - 18) * 1000
        income = np.random.normal(base_income, base_income * 0.2)
       
        # Rule: Credit score is influenced by age and income
        credit_score = min(850, max(300, int(600 + (age/80)*100 + (income/100000)*100 + np.random.normal(0, 50))))
       
        # Rule: Loan amount is based on income and credit score
        max_loan = income * (credit_score / 600)
        loan_amount = np.random.uniform(0, max_loan)
       
        data.append([age, income, credit_score, loan_amount])
   
    return pd.DataFrame(data, columns=['Age', 'Income', 'CreditScore', 'LoanAmount'])

df = generate_customer_data(1000)
df.head()

   Age        Income  CreditScore    LoanAmount
0   34  47571.718935          673   7598.086660
1   25  23328.309474          680  23748.329317
2   45  47630.987937          661  19580.840597
3   32  33707.101907          676   1523.866827
4   76  64284.428077          772  64521.395181

In [7]:
import simpy
import random
import pandas as pd

class Bank(object):
    def __init__(self, env, num_tellers):
        self.env = env
        self.teller = simpy.Resource(env, num_tellers)
       
    def service(self, customer):
        service_time = random.expovariate(1/10)  # Avg service time of 10 minutes
        yield self.env.timeout(service_time)

def customer(env, name, bank, data):
    arrival_time = env.now
    print(f'{name} arrives at the bank at {arrival_time:.2f}')
   
    with bank.teller.request() as request:
        yield request
        wait_time = env.now - arrival_time
        print(f'{name} waits for {wait_time:.2f}')
       
        yield env.process(bank.service(name))
       
        service_time = env.now - arrival_time
        print(f'{name} leaves the bank at {env.now:.2f}')
   
    # Append the customer data to the list
    data.append((name, arrival_time, wait_time, service_time))

def run_simulation(env, num_customers, bank, data):
    for i in range(num_customers):
        env.process(customer(env, f'Customer {i}', bank, data))
        yield env.timeout(random.expovariate(1/5))  # New customer every 5 minutes on average

# Set up and run the simulation
env = simpy.Environment()
bank = Bank(env, num_tellers=3)
num_customers = 100
data = []  # This will hold the customer data
env.process(run_simulation(env, num_customers, bank, data))
env.run()

# Create a DataFrame from the collected data
df = pd.DataFrame(data, columns=['Customer', 'ArrivalTime', 'WaitTime', 'ServiceTime'])
df.head()

Customer 0 arrives at the bank at 0.00
Customer 0 waits for 0.00
Customer 1 arrives at the bank at 0.78
Customer 1 waits for 0.00
Customer 1 leaves the bank at 2.21
Customer 2 arrives at the bank at 8.43
Customer 2 waits for 0.00
Customer 2 leaves the bank at 11.39
Customer 0 leaves the bank at 11.96
Customer 3 arrives at the bank at 13.22
Customer 3 waits for 0.00
Customer 3 leaves the bank at 14.48
Customer 4 arrives at the bank at 19.46
Customer 4 waits for 0.00
Customer 5 arrives at the bank at 20.04
Customer 5 waits for 0.00
Customer 6 arrives at the bank at 20.88
Customer 6 waits for 0.00
Customer 6 leaves the bank at 23.59
Customer 4 leaves the bank at 26.04
Customer 5 leaves the bank at 27.51
Customer 7 arrives at the bank at 30.80
Customer 7 waits for 0.00
Customer 7 leaves the bank at 34.75
Customer 8 arrives at the bank at 35.05
Customer 8 waits for 0.00
Customer 9 arrives at the bank at 40.35
Customer 9 waits for 0.00
Customer 9 leaves the bank at 46.61
Customer 8 leaves the bank at 46.70
Customer 10 arrives at the bank at 47.85
Customer 10 waits for 0.00
Customer 11 arrives at the bank at 60.96
Customer 11 waits for 0.00
Customer 12 arrives at the bank at 69.57
Customer 12 waits for 0.00
Customer 12 leaves the bank at 79.56
Customer 11 leaves the bank at 79.57
Customer 10 leaves the bank at 79.59
Customer 13 arrives at the bank at 80.28
Customer 13 waits for 0.00
Customer 14 arrives at the bank at 85.44
Customer 14 waits for 0.00
Customer 15 arrives at the bank at 86.15
Customer 15 waits for 0.00
Customer 13 leaves the bank at 87.58
Customer 16 arrives at the bank at 88.71
Customer 16 waits for 0.00
Customer 14 leaves the bank at 90.12
Customer 16 leaves the bank at 91.95
Customer 17 arrives at the bank at 102.46
Customer 17 waits for 0.00
Customer 15 leaves the bank at 103.16
Customer 18 arrives at the bank at 105.84
Customer 18 waits for 0.00
Customer 18 leaves the bank at 112.58
Customer 19 arrives at the bank at 114.35
Customer 19 waits for 0.00
Customer 17 leaves the bank at 118.31
Customer 20 arrives at the bank at 118.65
Customer 20 waits for 0.00
Customer 21 arrives at the bank at 118.86
Customer 21 waits for 0.00
Customer 19 leaves the bank at 120.40
Customer 22 arrives at the bank at 122.85
Customer 22 waits for 0.00
Customer 21 leaves the bank at 124.42
Customer 20 leaves the bank at 125.39
Customer 23 arrives at the bank at 126.02
Customer 23 waits for 0.00
Customer 22 leaves the bank at 127.56
Customer 24 arrives at the bank at 132.90
Customer 24 waits for 0.00
Customer 24 leaves the bank at 137.26
Customer 25 arrives at the bank at 137.98
Customer 25 waits for 0.00
Customer 23 leaves the bank at 139.06
Customer 25 leaves the bank at 142.16
Customer 26 arrives at the bank at 148.87
Customer 26 waits for 0.00
Customer 27 arrives at the bank at 151.24
Customer 27 waits for 0.00
Customer 28 arrives at the bank at 153.58
Customer 28 waits for 0.00
Customer 28 leaves the bank at 156.02
Customer 29 arrives at the bank at 158.14
Customer 29 waits for 0.00
Customer 27 leaves the bank at 158.78
Customer 29 leaves the bank at 165.03
Customer 30 arrives at the bank at 168.74
Customer 30 waits for 0.00
Customer 31 arrives at the bank at 170.44
Customer 31 waits for 0.00
Customer 31 leaves the bank at 172.35
Customer 32 arrives at the bank at 175.56
Customer 32 waits for 0.00
Customer 33 arrives at the bank at 176.46
Customer 34 arrives at the bank at 180.23
Customer 35 arrives at the bank at 180.27
Customer 32 leaves the bank at 180.45
Customer 33 waits for 3.99
Customer 36 arrives at the bank at 181.73
Customer 37 arrives at the bank at 181.89
Customer 33 leaves the bank at 182.39
Customer 34 waits for 2.17
Customer 34 leaves the bank at 182.41
Customer 35 waits for 2.14
Customer 38 arrives at the bank at 183.52
Customer 39 arrives at the bank at 184.23
Customer 30 leaves the bank at 192.71
Customer 36 waits for 10.98
Customer 36 leaves the bank at 192.99
Customer 37 waits for 11.10
Customer 40 arrives at the bank at 195.56
Customer 37 leaves the bank at 199.29
Customer 38 waits for 15.77
Customer 26 leaves the bank at 199.68
Customer 39 waits for 15.45
Customer 38 leaves the bank at 200.13
Customer 40 waits for 4.58
Customer 35 leaves the bank at 200.21
Customer 41 arrives at the bank at 203.14
Customer 41 waits for 0.00
Customer 42 arrives at the bank at 203.94
Customer 43 arrives at the bank at 206.20
Customer 40 leaves the bank at 208.15
Customer 42 waits for 4.20
Customer 39 leaves the bank at 209.55
Customer 43 waits for 3.35
Customer 44 arrives at the bank at 209.90
Customer 45 arrives at the bank at 216.24
Customer 46 arrives at the bank at 218.32
Customer 43 leaves the bank at 221.37
Customer 44 waits for 11.47
Customer 47 arrives at the bank at 224.64
Customer 48 arrives at the bank at 225.01
Customer 41 leaves the bank at 225.50
Customer 45 waits for 9.25
Customer 49 arrives at the bank at 225.64
Customer 45 leaves the bank at 226.00
Customer 46 waits for 7.68
Customer 44 leaves the bank at 226.61
Customer 47 waits for 1.97
Customer 42 leaves the bank at 227.33
Customer 48 waits for 2.32
Customer 46 leaves the bank at 227.59
Customer 49 waits for 1.96
Customer 48 leaves the bank at 229.55
Customer 50 arrives at the bank at 231.80
Customer 50 waits for 0.00
Customer 50 leaves the bank at 237.07
Customer 51 arrives at the bank at 237.95
Customer 51 waits for 0.00
Customer 47 leaves the bank at 238.32
Customer 51 leaves the bank at 241.35
Customer 52 arrives at the bank at 243.10
Customer 52 waits for 0.00
Customer 49 leaves the bank at 243.18
Customer 53 arrives at the bank at 243.36
Customer 53 waits for 0.00
Customer 53 leaves the bank at 245.53
Customer 54 arrives at the bank at 248.68
Customer 54 waits for 0.00
Customer 55 arrives at the bank at 248.99
Customer 55 waits for 0.00
Customer 56 arrives at the bank at 249.67
Customer 52 leaves the bank at 251.06
Customer 56 waits for 1.39
Customer 54 leaves the bank at 251.43
Customer 57 arrives at the bank at 252.21
Customer 57 waits for 0.00
Customer 58 arrives at the bank at 256.94
Customer 57 leaves the bank at 259.08
Customer 58 waits for 2.14
Customer 59 arrives at the bank at 259.71
Customer 60 arrives at the bank at 261.69
Customer 56 leaves the bank at 262.33
Customer 59 waits for 2.62
Customer 61 arrives at the bank at 267.14
Customer 55 leaves the bank at 269.55
Customer 60 waits for 7.86
Customer 62 arrives at the bank at 274.12
Customer 60 leaves the bank at 275.64
Customer 61 waits for 8.50
Customer 59 leaves the bank at 280.36
Customer 62 waits for 6.24
Customer 63 arrives at the bank at 285.34
Customer 64 arrives at the bank at 290.08
Customer 58 leaves the bank at 290.20
Customer 63 waits for 4.86
Customer 65 arrives at the bank at 290.26
Customer 66 arrives at the bank at 293.52
Customer 61 leaves the bank at 295.31
Customer 64 waits for 5.23
Customer 62 leaves the bank at 297.48
Customer 65 waits for 7.22
Customer 63 leaves the bank at 301.49
Customer 66 waits for 7.97
Customer 67 arrives at the bank at 304.41
Customer 66 leaves the bank at 304.48
Customer 67 waits for 0.06
Customer 65 leaves the bank at 305.17
Customer 64 leaves the bank at 305.36
Customer 68 arrives at the bank at 305.89
Customer 68 waits for 0.00
Customer 69 arrives at the bank at 306.49
Customer 69 waits for 0.00
Customer 69 leaves the bank at 308.35
Customer 67 leaves the bank at 309.00
Customer 68 leaves the bank at 309.46
Customer 70 arrives at the bank at 312.10
Customer 70 waits for 0.00
Customer 71 arrives at the bank at 313.65
Customer 71 waits for 0.00
Customer 70 leaves the bank at 315.77
Customer 72 arrives at the bank at 316.02
Customer 72 waits for 0.00
Customer 72 leaves the bank at 318.49
Customer 71 leaves the bank at 321.37
Customer 73 arrives at the bank at 325.08
Customer 73 waits for 0.00
Customer 73 leaves the bank at 328.42
Customer 74 arrives at the bank at 332.53
Customer 74 waits for 0.00
Customer 74 leaves the bank at 334.58
Customer 75 arrives at the bank at 336.71
Customer 75 waits for 0.00
Customer 76 arrives at the bank at 337.66
Customer 76 waits for 0.00
Customer 75 leaves the bank at 341.02
Customer 77 arrives at the bank at 341.70
Customer 77 waits for 0.00
Customer 76 leaves the bank at 341.73
Customer 78 arrives at the bank at 345.67
Customer 78 waits for 0.00
Customer 79 arrives at the bank at 352.47
Customer 79 waits for 0.00
Customer 77 leaves the bank at 353.14
Customer 80 arrives at the bank at 355.26
Customer 80 waits for 0.00
Customer 81 arrives at the bank at 355.61
Customer 78 leaves the bank at 355.99
Customer 81 waits for 0.38
Customer 80 leaves the bank at 356.86
Customer 81 leaves the bank at 359.79
Customer 79 leaves the bank at 364.93
Customer 82 arrives at the bank at 372.87
Customer 82 waits for 0.00
Customer 83 arrives at the bank at 375.99
Customer 83 waits for 0.00
Customer 84 arrives at the bank at 377.26
Customer 84 waits for 0.00
Customer 84 leaves the bank at 378.04
Customer 83 leaves the bank at 380.26
Customer 85 arrives at the bank at 390.74
Customer 85 waits for 0.00
Customer 86 arrives at the bank at 397.29
Customer 86 waits for 0.00
Customer 82 leaves the bank at 397.86
Customer 87 arrives at the bank at 401.01
Customer 87 waits for 0.00
Customer 88 arrives at the bank at 403.42
Customer 85 leaves the bank at 403.49
Customer 88 waits for 0.08
Customer 87 leaves the bank at 404.78
Customer 88 leaves the bank at 406.94
Customer 89 arrives at the bank at 416.84
Customer 89 waits for 0.00
Customer 90 arrives at the bank at 417.11
Customer 90 waits for 0.00
Customer 86 leaves the bank at 422.29
Customer 91 arrives at the bank at 422.98
Customer 91 waits for 0.00
Customer 90 leaves the bank at 430.58
Customer 92 arrives at the bank at 431.22
Customer 92 waits for 0.00
Customer 92 leaves the bank at 435.27
Customer 93 arrives at the bank at 435.64
Customer 93 waits for 0.00
Customer 93 leaves the bank at 438.50
Customer 94 arrives at the bank at 439.33
Customer 94 waits for 0.00
Customer 94 leaves the bank at 439.98
Customer 95 arrives at the bank at 440.85
Customer 95 waits for 0.00
Customer 96 arrives at the bank at 440.86
Customer 97 arrives at the bank at 443.22
Customer 91 leaves the bank at 443.49
Customer 96 waits for 2.62
Customer 98 arrives at the bank at 444.57
Customer 96 leaves the bank at 445.06
Customer 97 waits for 1.84
Customer 89 leaves the bank at 448.40
Customer 98 waits for 3.83
Customer 95 leaves the bank at 450.21
Customer 97 leaves the bank at 450.88
Customer 99 arrives at the bank at 454.89
Customer 99 waits for 0.00
Customer 99 leaves the bank at 458.66
Customer 98 leaves the bank at 462.76

     Customer  ArrivalTime  WaitTime  ServiceTime
0  Customer 1     0.778601       0.0     1.435578
1  Customer 2     8.427726       0.0     2.960750
2  Customer 0     0.000000       0.0    11.958757
3  Customer 3    13.218346       0.0     1.263081
4  Customer 6    20.882672       0.0     2.708268